ALTER TYPE "KnowledgeRelationshipType" ADD VALUE IF NOT EXISTS 'FILE_MOVED_TO';
ALTER TYPE "KnowledgeRelationshipType" ADD VALUE IF NOT EXISTS 'FILE_RENAMED_TO';
ALTER TYPE "KnowledgeRelationshipType" ADD VALUE IF NOT EXISTS 'FILE_GROUPED_WITH';
ALTER TYPE "KnowledgeRelationshipType" ADD VALUE IF NOT EXISTS 'FILE_USED_IN_PLAN';
ALTER TYPE "KnowledgeRelationshipType" ADD VALUE IF NOT EXISTS 'FILE_INCLUDED_IN_EXECUTION';
